### ISSUE TITLE
don't exit when --yesno is used

### ISSUE THREAD

**Issue by lnussel** [openSUSE/jeos-firstboot#110]
the `d()` abstraction exits on exit code 1 which is normally cancel. The yesno dialog is special though. The absolutely valid 'no' reply also maps to exit code 1. So the function should probably catch that special case to avoid having to call dialog manually all over the script.

**Comment by Vogtinator** [comment]
Or a new `d_yesno` function could be created.

**Comment by lnussel** [comment]
sure. or make it transparent to avoid surprises like me :)

**Comment by Vogtinator** [comment]
The `d` method is somewhat misleading anyway, as it does multiple things which are only needed in specific cases:

1. Capture output in `$result`, only needed for input
2. Prompt on exit and exit if acknowleged. Only needed for "steps", not most dialogs. The "confirm root password" dialog for instance shouldn't use this either, but actually go back. Error messages don't need that either...

And then it sets `--backtitle` which is actually useful everywhere.

This mess should be untangled in a bigger refactor IMO...

**Comment by Vogtinator** [comment]
https://github.com/openSUSE/jeos-firstboot/pull/113
