### ISSUE TITLE
Use `snapper --no-dbus` on Leap 42.3/SLE12SP3

### ISSUE THREAD

**Issue by mnowaksuse** [openSUSE/jeos-firstboot#14]
```shell
# we can't use snapper here due to missing dbus daemon in
# firstboot. So we have to create a snapshot manually.
#snapper --no-dbus -v create -d "Factory Status" --userdata "important=yes"
mkdir ".snapshots/$num"
btrfs subvolume snapshot -r / ".snapshots/$num/snapshot"
```
`snapper` since version 0.4.0 supports `--no-dbus` for all commands: http://snapper.io/2016/12/19/no-dbus-for-all.html. Perhaps it can be now used instead of the manual crafting of the snapshot et al.?

**Comment by Vogtinator** [comment]
I wonder why it has a snapper call above but it's commented out - maybe there is a reason.

@gmoro, @lnussel: Do you remember?

**Comment by mnowaksuse** [comment]
We test `snapper --no-dbus` in openQA extensively now. It _should_ work for our use case.

**Comment by gmoro** [comment]
I think we are safe to assume no older version where this can causes problem will uses later releases of jeos-firstboot, we could try and change that to snapper again and test it.

**Comment by Vogtinator** [comment]
Actually, after 3d5d163ddbb89737791dc3e712e15fb7898c871e we should have a dbus daemon now.

**Comment by Vogtinator** [comment]
https://github.com/openSUSE/jeos-firstboot/pull/46 implements this as well.

**Comment by Vogtinator** [comment]
> #46 implements this as well.

Which is now merged, so closing
