### ISSUE TITLE
Refuse to deploy JeOS in case of error in jeos-firstboot

### ISSUE THREAD

**Issue by mnowaksuse** [openSUSE/jeos-firstboot#15]
Recently we lost `btrfs` binary from JeOS: https://openqa.opensuse.org/tests/384539#step/firstrun/7 therefor JeOS is unable to deploy properly, but it deploys anyway.

Perhaps `jeos-firstboot` needs to fail more spectacularly and refuse to deploy in case of error. Perhaps by `set -e` in it's libraries?

**Comment by Vogtinator** [comment]
If the quota setup fails, a warning is displayed, fatal errors result in a poweroff and repeated attempt on the next boot now with #31
