### ISSUE TITLE
jeos-firstboot calls modprobe in "containers"

### ISSUE THREAD

**Issue by lnussel** [openSUSE/jeos-firstboot#56]
running jeos-firstboot eg in WSL it still tries to call modprobe which doesn't work of course. Editing /etc/sysconfig/bootloader seems like a rather dirty hack anyways. Maybe should be moved to a hook that can be disabled instead,

**Comment by lnussel** [comment]
(or at least check if there is a bootloader before modprobe)

**Comment by Vogtinator** [comment]
Please try the linked PR.
