### ISSUE TITLE
network settings are unconditional

### ISSUE THREAD

**Issue by lnussel** [openSUSE/jeos-firstboot#57]
the network detection and configuration is unconditional. It may not be needed if the image already has network configured or there is nothing to do actually, like in WSL

**Comment by Vogtinator** [comment]
Yes, but the detection is there to check for that.

**Comment by lnussel** [comment]
IIRC I saw errors from udevadm which doesnt work in WSL

**Comment by Vogtinator** [comment]
Sounds like in those cases it could just be skipped then
