### ISSUE TITLE
Add an option to skip the EULA

### ISSUE THREAD

**Issue by aplanas** [openSUSE/jeos-firstboot#63]
An use case for jeos-firstboot is to pre-configure the locale and the network from an image that is part of a different process, like a pxeboot. Any user interaction, like accepting an EULA, will break the use case.

Normally this pxe boot image will be based on openSUSE (TW / Leap) or SLE, and will be part of a product where we already accepted an EULA.

Add an option that can skip the EULA so we can build those components that do not allow user interaction.

**Comment by Vogtinator** [comment]
As those images can only be downloaded if the license was already agreed to (part of an rpm), an option such as `EULA_AGREED=yes` in `jeos-frstiboot.conf` makes sense.

**Comment by aplanas** [comment]
Ah, good point about the name. The PR use `JEOS_SKIP_EULA`, maybe makes more sense to use `JEOS_EULA_ALREADY_AGREED`
