### ISSUE TITLE
Add an option to hide the SUSEConnect dialog on SLE

### ISSUE THREAD

**Issue by aplanas** [openSUSE/jeos-firstboot#65]
When developing a PXE boot image based on SLE, we may want to hide the SUSEConnect dialog to avoid any user interaction.

**Comment by Vogtinator** [comment]
If there is no reason for registration, simply don't install SUSEConnect. Not only does that avoid pulling in ruby, it also disables the dialog.

**Comment by aplanas** [comment]
Actually I need to install SUSEConnect in any image, based on Leap, TW or SLE. That is why there is a [condition](https://github.com/openSUSE/jeos-firstboot/blob/master/files/usr/lib/jeos-firstboot#L336) over the ID.
