### ISSUE TITLE
skip instructions for en_US

### ISSUE THREAD

**Issue by lnussel** [openSUSE/jeos-firstboot#68]
Just noticed that the wizard has some informative dialog in case glibc-locale is not installed:
https://openqa.opensuse.org/tests/1257590#step/firstrun/1

The dialog should not be shown IMO. The firstboot wizard is not there to educate, it doesn't tell about other things to customize either after all. So if there are no locales to choose from, just skip that step silently.

**Comment by gmoro** [comment]
I think the decision to leave a dialog was the fact that previous versions would always show the locale selection dialog, so to keep the steps the same as previous. But I do agree that the dialog is pointless. Will raise this with Vincent and see what he thinks.

**Comment by Vogtinator** [comment]
This was a requirement for dropping locales by default in SLE 15 SP1 AFAIK.

If documented in the release notes, we can probably drop it.

**Comment by vmoutoussamy** [comment]
[jsc#PM-2100 - Removing the local warning from jeosfirstboot](https://jira.suse.com/browse/PM-2100)

**Comment by Vogtinator** [comment]
Done with #70
