### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by gmoro** [openSUSE/jeos-firstboot#76]
First early draft here https://github.com/gmoro/jeos-firstboot/tree/gmoro-readme

This issue might need improvement in other parts of the documentation so we can link it here.

**Comment by Vogtinator** [comment]
If you open a PR, reviewing is easier

**Comment by Vogtinator** [comment]
> This is a lightweight, dialog based firstboot wizard that replaces systemd's line based firstboot program.

It actually calls `systemd-firstboot` itself, so it's not really a replacement

> It can show the license and prompt for language, keyboard, timezone, root passsword and network configuration.

Should also mention that it can be extended with modules

**Comment by Vogtinator** [comment]
Installation instructions are missing and it would also be useful to have, along side with some hints on how to develop on this

**Comment by vmoutoussamy** [comment]
I agree with Fabian comments below, however the README draft should be pushed live IMHO, no need to hold it back.

**Comment by gmoro** [comment]
closed by https://github.com/openSUSE/jeos-firstboot/pull/77
