### ISSUE TITLE
Documentaion on firstboot.conf and exporting

### ISSUE THREAD

**Issue by kagehisa** [openSUSE/jeos-firstboot#85]
I'm planning to use JeOS for our HyperV based environment instead of regular SLES images. Mostly because of the [here](https://en.opensuse.org/Portal:JeOS) mentioned possibility to configure most settings with a config file for firstboot.
Now that I'm playing around with it there is no real documentation on how to export a given configuration or how to set a password or configure the network via the config file. Is there any Information on this?

**Comment by Vogtinator** [comment]
The documentation is the example config file:

https://github.com/openSUSE/jeos-firstboot/blob/master/files/usr/share/defaults/jeos-firstboot.conf

Just put any config into `/etc/defaults/jeos-firstboot.conf` or copy the whole file.

**Comment by kagehisa** [comment]
Ok so there is no way to configure the network settings vie the config file?

**Comment by Vogtinator** [comment]
No, but you can create the `/etc/sysconfig/network/ifcfg-*` file directly instead.

**Comment by kagehisa** [comment]
Ok, thanks for the help.

**Comment by Vogtinator** [comment]
I should mention though that `jeos-firstboot` tries to create a DHCP config for all interfaces which get an IP over DHCP successfully, so that might interfere in some setups. Maybe there should be an option to disable that or `jeos-firstboot` should just ignore interfaces with an existing config (or both).

**Comment by kagehisa** [comment]
Ok, that explains why configure network via jeos-config does nothing in my case..
