### ISSUE TITLE
Make use of shellcheck

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/jeos-firstboot#95]
https://www.shellcheck.net checks bash (and other shell) scripts for errors and possible bugs, we could make use of that for CI.
This would probably require quite a few fixes and shellcheck ignores to make it really useful though.
Needs some experimenting.

**Comment by gmoro** [comment]
I tried that before, but had no time to really put it to use, would be a great addition

**Comment by Vogtinator** [comment]
We should try to use relative source paths for inclusion to fix issues like

```
In files/usr/sbin/jeos-config line 23:
. "/usr/share/jeos-firstboot/jeos-firstboot-functions"
  ^-- SC1091 (info): Not following: /usr/share/jeos-firstboot/jeos-firstboot-functions was not specified as input (see shellcheck -x).
```

e.g. in `jeos-firstboot` and `jeos-config` do `cd "$(dirname $0)"` to ensure we're in the right location and then use `. ../share/jeos-firstboot/...`. That would also make it possible to test without installing it system-wide.
